name: Build Say Gay firmware
on:
  push:
    paths:
      - "config/say_gay*"
      - "build/build_say_gay.yaml"
      - ".github/workflows/build_say_gay.yml"  
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build/build_say_gay.yaml
