name: Build Nice!Nano settings reset
on:
  push:
    paths:
      - "config/nice_nano_reset*"
      - "build/build_nice_nano_reset.yaml"
      - ".github/workflows/build_nice_nano_reset.yml"  
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build/build_nice_nano_reset.yaml
