name: Build firmware - Swept Corne
on:
  push:
    paths:
      - "config/swept_corne*"
      - "build/build_swept_corne.yaml"
      - ".github/workflows/build_swept_corne.yml"  
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build/build_swept_corne.yaml
      archive_name: swept_corne
