name: Build ZMK firmware
on:
  push:
    paths:
      - "config/**"
      - "boards/**"
      - "build.yaml"
      - ".github/workflows/build.yml"  
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
