name: Build all firmware
on:
  push:
    paths:
      - "build/build_all.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build/build_all.yaml
      archive_name: build_all
